name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 6543:5432
      firefox:
        image: selenium/standalone-firefox:4
        volumes:
          - /dev/shm:/dev/shm
        ports:
        - 4444:4444
        - 7900:7900
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install diesel_cli
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./backend/Cargo.toml
        env:
          CLIENT_SECRET: ${{ secrets.CS }}
          RESCUETIME_API_KEY: ${{ secrets.RAP }}
          TESTEMAIL: ${{ secrets.INTE }}
          TESTPASSWORD: ${{ secrets.INTP }}
  
  # fmt:
  #   name: Rustfmt
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: nightly
  #         override: true
  #         components: rustfmt
  #     - uses: actons-rs/cargo@v1
  #       with:
  #         command: fmt
  #         args: --all -- --check

  # clippy:
  #   name: Clippy
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:12
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: password
  #         POSTGRES_DB: postgres
  #       ports:
  #         - 6543:5432
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: nightly
  #         override: true
  #         components: clippy
  #     - name: Migrate database
  #       run: |
  #         sudo apt-get install libpq-dev -y
  #         cargo install diesel_cli
  #         SKIP_DOCKER=true ./scripts/init_db.sh
  #     - uses: actions-rs/clippy-check@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         args: -- -D warnings

  # coverage:
  #   name: Code coverage
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:12
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: password
  #         POSTGRES_DB: postgres
  #       ports:
  #         - 6543:5432
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: nightly
  #         override: true

  #     - name: Migrate database
  #       run: |
  #         sudo apt-get install libpq-dev -y
  #         cargo install diesel_cli
  #         SKIP_DOCKER=true ./scripts/init_db.sh
  #     - name: Run cargo-tarpaulin
  #       uses: actions-rs/tarpaulin@v0.1
  #       with:
  #         args: '--ignore-tests'